#Backdoor Detector Configuration
#Sat Jun 27 21:31:32 ICT 2026
enable_gemini_2=true
gemini_api_key=
gemini_api_key_2=
gemini_model=gemini-3.5-flash
gemini_model_2=gemini-3-flash-preview
ai_parallel_scanning=false
analyzer_parallel_threads=3
primary_ai=backend
