package backdoordetected.cache;

import backdoordetected.utils.StandaloneLogger;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.logging.Logger;

public class FileRiskClassifier {
    private static final Logger logger = StandaloneLogger.getLogger();

    public enum RiskLevel {
        SKIP,
        LOW,
        MEDIUM,
        HIGH
    }

    public static RiskLevel classifyFile(Path file) throws IOException {
        String content = Files.readString(file);
        String path = file.toString();
        if (isTestFile(path, content)) {
            logger.fine("Skipping test file: " + file.getFileName());
            return RiskLevel.SKIP;
        }
        if (isGeneratedCode(content)) {
            logger.fine("Skipping generated code: " + file.getFileName());
            return RiskLevel.SKIP;
        }
        if (isHighRiskFile(content)) {
            logger.fine("High-risk file detected: " + file.getFileName());
            return RiskLevel.HIGH;
        }
        if (isSimplePOJO(content)) {
            logger.fine("Low-risk POJO detected: " + file.getFileName());
            return RiskLevel.LOW;
        }
        return RiskLevel.MEDIUM;
    }

    private static boolean isTestFile(String path, String content) {
        if (path.contains("/test/") || path.contains("\\test\\") ||
                path.contains("/tests/") || path.contains("\\tests\\")) {
            return true;
        }

        return content.contains("@Test") ||
                content.contains("import org.junit") ||
                content.contains("import org.testng") ||
                content.contains("extends TestCase");
    }

    private static boolean isGeneratedCode(String content) {
        return content.contains("@Generated") ||
                content.contains("// Auto-generated") ||
                content.contains("// Generated by") ||
                content.contains("// DO NOT EDIT") ||
                content.contains("@javax.annotation.Generated");
    }

    private static boolean isHighRiskFile(String content) {
        if (content.contains("implements Listener") ||
                content.contains("@EventHandler")) {
            return true;
        }
        if (content.contains("implements CommandExecutor") ||
                content.contains("implements TabCompleter") ||
                content.contains("onCommand(")) {
            return true;
        }
        if (content.contains("Runtime.getRuntime()") ||
                content.contains("ProcessBuilder") ||
                content.contains("Class.forName") ||
                content.contains("Method.invoke")) {
            return true;
        }

        return false;
    }

    private static boolean isSimplePOJO(String content) {
        boolean noDangerousPatterns = !content.contains("Runtime.getRuntime()") &&
                !content.contains("ProcessBuilder") &&
                !content.contains("Class.forName") &&
                !content.contains("Method.invoke") &&
                !content.contains("exec(") &&
                !content.contains("@EventHandler") &&
                !content.contains("implements Listener");

        if (!noDangerousPatterns) {
            return false;
        }
        int publicMethods = countOccurrences(content, "public ");
        int privateMethods = countOccurrences(content, "private ");
        int totalMethods = publicMethods + privateMethods;
        if (totalMethods > 15) {
            return false;
        }
        int getters = countOccurrences(content, "public get");
        int setters = countOccurrences(content, "public set");
        int accessors = getters + setters;
        return publicMethods > 0 && (accessors * 100 / publicMethods) > 70;
    }

    private static int countOccurrences(String str, String pattern) {
        if (pattern.isEmpty()) {
            return 0;
        }
        int count = 0;
        int index = 0;
        while ((index = str.indexOf(pattern, index)) != -1) {
            count++;
            index += pattern.length();
        }
        return count;
    }

    public static class Stats {
        public int skipped = 0;
        public int low = 0;
        public int medium = 0;
        public int high = 0;

        public void record(RiskLevel level) {
            switch (level) {
                case SKIP -> skipped++;
                case LOW -> low++;
                case MEDIUM -> medium++;
                case HIGH -> high++;
            }
        }

        public int total() {
            return skipped + low + medium + high;
        }

        public int analyzed() {
            return low + medium + high;
        }

        @Override
        public String toString() {
            return String.format(
                    "File Classification: %d total, %d skipped (%.1f%%), %d analyzed (%d high, %d medium, %d low)",
                    total(), skipped, (skipped * 100.0 / total()), analyzed(), high, medium, low);
        }
    }
}
